app = "edukraft"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = "edukraft_data"
  destination = "/data"

[env]
  PORT = "8080"
  DB_PATH = "/data/edukraft.db"
  NODE_ENV = "production"
  CORS_ORIGINS = "*"
